### ISSUE TITLE
Anvil segfault on launch via --x11 on Debian

### ISSUE THREAD

**Issue by aurabindo** [Smithay/smithay#438] opened 2021-12-20 15:11 UTC
Running `cargo run -- --x11` on Debian 11 gives a segfault with the below error:
```
Dec 20 10:08:34.379 INFO Starting anvil with x11 backend
Dec 20 10:08:34.379 INFO Connecting to the X server, smithay_module: backend_x11
Dec 20 10:08:34.380 INFO Connected to screen 0, smithay_module: backend_x11
Dec 20 10:08:34.380 INFO Loaded extension Present version 1.0, smithay_module: backend_x11
Dec 20 10:08:34.381 INFO Loaded extension XFIXES version 4.0, smithay_module: backend_x11
Dec 20 10:08:34.381 INFO Loaded extension DRI3 version 1.0, smithay_module: backend_x11
Dec 20 10:08:34.382 DEBG Supported EGL client extensions: ["EGL_EXT_device_base", "EGL_EXT_device_enumeration", "EGL_EXT_device_query", "EGL_EXT_platform_base", "EGL_KHR_client_get_all_proc_addresses", "EGL_EXT_client_extensions", "EGL_KHR_debug", "EGL_EXT_platform_device", "EGL_EXT_platform_wayland", "EGL_KHR_platform_wayland", "EGL_EXT_platform_x11", "EGL_KHR_platform_x11", "EGL_MESA_platform_gbm", "EGL_KHR_platform_gbm", "EGL_MESA_platform_surfaceless"], smithay_module: backend_egl
Segmentation fault
```

**Comment by Drakulix** [comment] 2021-12-20 16:29
Can you provide a backtrace?

**Comment by aurabindo** [comment] 2021-12-21 16:16
@Drakulix  I ran with RUST_BACKTRACE=1 but there are no backtraces. It appears the segfault is coming from another thread. I see the crash happening at different locations.

**Comment by Drakulix** [comment] 2021-12-21 16:24
Could you run anvil through gdb and then copy what falls out of the `bt` command once it segfaults?

Wild guess, but maybe its crashing in the graphics driver. Are you by chance running on a slightly unusual setup?

**Comment by aurabindo** [comment] 2021-12-23 01:41
I just moved from Debian to Ubuntu and now I cant get this crash. I dont think there is anything unusual about by graphics setup. its dual display and slightly older AMD Oland graphics.

![image](https://user-images.githubusercontent.com/1412512/147174648-61d0e260-2833-4009-8723-bedf59a4896b.png)

 I'm kinda lazy to install debian back for a repro.. sorry :-|

**Comment by h1771t** [comment] 2022-06-17 11:34
I installed deb 11 on qemu, build and run anvil. I can reproduce this seg fault. Here is the gdb bt output. [output.txt](https://github.com/Smithay/smithay/files/8927050/output.txt)

On deb 11 default system packages for me look as follows:
```
u1@debian:~/smithay$ dpkg -l |grep libegl
ii  libegl-mesa0:amd64                    20.3.5-1                         amd64        free implementation of the EGL API -- Mesa vendor library
ii  libegl1:amd64                         1.3.2-1                          amd64        Vendor neutral GL dispatch library -- EGL support
```

The library files look as follows:
```
u1@debian:/usr/lib/x86_64-linux-gnu$ ls -l *EGL*
lrwxrwxrwx 1 root root     20 Mar 25  2021 libEGL_mesa.so.0 -> libEGL_mesa.so.0.0.0
-rw-r--r-- 1 root root 263416 Mar 25  2021 libEGL_mesa.so.0.0.0
lrwxrwxrwx 1 root root     15 Jul 29  2020 libEGL.so.1 -> libEGL.so.1.1.0
-rw-r--r-- 1 root root  80352 Jul 29  2020 libEGL.so.1.1.0
```

If you'd like me to try different things to see outputs, please let me know

**Comment by h1771t** [comment] 2022-06-17 11:44
For comparison, here are the lib versions in Pop!_os 22.04
```
u1@pop-os:~$ dpkg -l|grep egl
ii  libegl-mesa0:amd64                      22.0.1-1ubuntu2                                                 amd64        free implementation of the EGL API -- Mesa vendor library
ii  libegl1:amd64                           1.4.0-1                                                         amd64        Vendor neutral GL dispatch library -- EGL support
ii  libwayland-egl1:amd64                   1.20.0-1                                                        amd64        wayland compositor infrastructure - EGL library
```
And files for the libs:
```
u1@pop-os:~$ ls /usr/lib/x86_64-linux-gnu/*EGL*
/usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0      /usr/lib/x86_64-linux-gnu/libEGL.so.1
/usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0.0.0  /usr/lib/x86_64-linux-gnu/libEGL.so.1.1.0
```

**Comment by Drakulix** [comment] 2022-06-17 12:52
So according to the backtrace this segfault happens inside mesa when calling `eglInitialize`.

To fully analyse this we would need mesa with debug symbols, but we can speculate.

Because this seems to happen with the `X11DefaultDisplay` initializer for egl, which corresponds to passing a null-ptr to `eglInitialize`, it might be, that older mesa-versions are not handling that well, expecting a valid display. It is legal according to the extension anvil is using, but that functionality could be broken.

A few follow up questions could help us debug that:
- Can somebody build debian's mesa version with debug symbols and get a backtrace?
- Does it work on debian with winit's x11 backend?
- Does the x11 backend work with the code on the `feature/x11_surface` branch? That would be another reason to merge #524

**Comment by h1771t** [comment] 2022-06-17 13:42
Thanks. 

--winit fails on master for a different reason, not a segfault but it panics. --winit on feature/x11_eglsurface does launch with success, but seems no inputs work (maybe still WIP?)

--x11 segfaults on master and also fails on feature/x11_eglsurface but with a different reason, as attached. It cannot connect it seems and then on its way out segfaults: 
[output.txt](https://github.com/Smithay/smithay/files/8927981/output.txt)

`CRIT Event thread exiting due to connection error Unknown connection error, smithay_module: backend_x11`

So maybe the master branch segfault is not worth looking at if feature/x11_eglsurface is doing to replace it? If so, I can look a bit into why the --x11 connection fails on the feature/x11_eglsurface branch if needed

**Comment by h1771t** [comment] 2022-06-17 14:01
So the error above on feature/x11_eglsurface for --x11 is unrelated to connecting. If I comment out `xlib_sys::xlib::XCloseDisplay(*self.display);` in *src/backend/x11/conn.rs* inside the `impl Drop for X11Connection {` then it is working. The window launches and it looks fine. So --x11 does indeed work on feature/x11_eglsurface branch in debian 11.

**Comment by Drakulix** [comment] 2022-06-17 15:17
We are not sure yet, if the `feature/x11_eglsurface` branch is going to be merged into smithay. It replaces code currently working just fine on recent mesa versions, that is integrating well with our event loop, with a more conservative approach (similar to how winit is working internally), that does not integrate nearly as nicely. However that was required by earlier nvidia-driver version to get the x11-backend working there. So it is not surprising to me, that it is working with older mesa-versions as well.

So thanks for taking your time checking out that (rather outdated) branch, it serves as another argument, why we *might* have to reconsider how our X11 backend operates.

**Comment by h1771t** [comment] 2022-06-17 17:49
> Can somebody build debian's mesa version with debug symbols and get a backtrace?

Ah okay. No prob. I will try the above next, with smithay master branch and see what I can find

**Comment by h1771t** [comment] 2022-06-17 18:52
gdb output after debian 11 package libegl-mesa0-dbgsym installed:
[output.txt](https://github.com/Smithay/smithay/files/8929933/output.txt)

**Comment by h1771t** [comment] 2022-06-18 11:39
And the difference of function `dri2_find_screen_for_display` in mesa 20.3 vs 22.0:
https://gitlab.freedesktop.org/mesa/mesa/-/blob/20.3/src/egl/drivers/dri2/platform_x11.c#L1210
https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.0/src/egl/drivers/dri2/platform_x11.c#L1210

I wonder if this should be fixed in debian rather than smithay?

**Comment by Drakulix** [comment] 2022-06-19 15:03
I mean, if these two lines could be backported to mesa 20.*, it should work:
https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.0/src/egl/drivers/dri2/platform_x11.c#L1214-1215

**Comment by h1771t** [comment] 2022-06-20 08:42
> I mean, if these two lines could be backported to mesa 20.*, it should work:

I am reaching out to debian 11 package maintainers for libegl-mesa, as well as the mesa3d project, to see where best this fix can be backported upstream. I'm not sure if mesa3d versions have lifespan or eol dates (I cannot find any), so maybe the fix belongs to mesa3d and debian 11 picks it up as an update; not sure so trying both to see what happens

**Comment by Venemo** [comment] 2022-06-21 07:49
In a nutshell, mesa 20.x is no longer supported and if you use mesa 20.x, that means you won't benefit from any improvements made to the graphics stack since late 2020 and are likely to find issues.

If you distro ships a mesa release which is no longer supported, please ask your distro maintainers to upgrade to a supported stable version.

Mesa has a [release calendar](https://docs.mesa3d.org/release-calendar.html) that shows you the upcoming versions and estimated date of their release. Only the last two point releases get stable updates (at the time of writing, these are 22.1 and 22.2). Mesa 20.3 was released in December 2020 and is no longer supported or updated. We recommend that users **don't use unsupported mesa releases** due to lack of new hardware support, bug fixes, and compatibility. You are likely to encounter problems if you try to play newer than 2020 games and you will also get no HW acceleration for any HW that was launched since 2020, and poor support for HW which was launched near the end of 2020.

**Comment by Drakulix** [comment] 2022-06-21 10:09
That settles it then, if mesa 20.x is officially unsupported, smithay won't make an attempt in supporting it. That is just not feasible from a maintenance perspective.

So Debian has to either update mesa (which seems to be the recommended solution, though potentially difficult with their conservative upgrade strategy) or manually backport the required fix.

**Closed by Drakulix** 2022-06-21 10:09 UTC
Labels: component: backend, status: needs investigation, component: anvil

**Comment by Venemo** [comment] 2022-06-21 11:07
Considering they call it Debian "stable", I think it's reasonable to ask them to upgrade to a stable, supported version of mesa.

**Comment by h1771t** [comment] 2022-06-21 11:16
Thank you. I will ask the debian package maintainers if this is feasible for them, or else if not then at least backport the fix. Either way smithay is probably going to have a mesa > 21 requirement initially. If debian 11 won't do either of the needed steps, it just won't be a supported distro for smithay/cosmic-comp then.
